export default {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '\\.(css|less|sass|scss)$': 'identity-obj-proxy',
    '\\.(gif|ttf|eot|svg|png)$': '<rootDir>/src/test/__mocks__/fileMock.js',
  },
  setupFilesAfterEnv: ['<rootDir>/src/setup-tests.ts'],
  collectCoverage: true,
  collectCoverageFrom: [
    'src/**/*.{js,jsx,ts,tsx}',
    'src/**/**/*.{js,jsx,ts,tsx}',
    'src/**/**/**/*.{js,jsx,ts,tsx}',
    'src/**/**/**/**/*.{js,jsx,ts,tsx}',
    '!src/**/*.d.ts',
    '!src/lib/*.d.ts',
    '!src/lib/*.ts',
    '!src/lib/**/*.ts',
    '!src/services/*.d.ts',
    '!src/services/**/*.d.ts',
    '!src/services/**/**/*.d.ts',
    '!src/main.tsx',
    '!src/layout.tsx',
    '!src/App.tsx',
    '!src/services/*.tsx',
    '!src/services/*.ts',
    '!src/services/**/*.tsx',
    '!src/services/**/*.ts',
    '!src/services/**/**/*.tsx',
    '!src/utils/**/*.tsx',
    '!src/utils/*.tsx',
    '!src/utils/**/*.ts',
    '!src/utils/*.ts',
    '!src/utils',
    '!**/*.stories.{js,jsx,ts,tsx}',
    '!src/theme/theme-provider.tsx',
    '!src/routes/endpoints.ts',
    '!src/routes/router.ts',
    '!src/ui/*.ts',
    '!src/ui/**/*.ts',
    '!src/assets/*.tsx',
    '!src/pages/index.ts',
    '!src/components/ui/*.tsx',
    '!src/components/ui/**/*.tsx',
  ],
  coverageReporters: ['json', 'lcov', 'text', 'clover'],
  testPathIgnorePatterns: [
    '/node_modules/',
    'pipelines/',
    'public/',
    'src/test/',
    'src/lib/',
    'src/services/config/',
    'src/services/',
    'src/assets/',
    'src/@types/',
    '/manifests/',
    '/storybook/',
    '/husky/',
  ],
  watchPathIgnorePatterns: ['/node_modules/'],
  modulePathIgnorePatterns: ['<rootDir>/src/test/__mocks__/fileMock.js'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  transform: {
    '^.+\\.(ts|tsx)$': 'ts-jest',
  },
};
