export const Icons = {
	js: () => import('@/public/icons/js.png'),
	css3: () => import('@/public/icons/css3.png'),
	html: () => import('@/public/icons/html5.png'),
	reactjs: () => import('@/public/icons/reactjs.png'),
	typescript: () => import('@/public/icons/typescript.png'),
	graphql: () => import('@/public/icons/graphql.png'),
	jest: () => import('@/public/icons/jest.png'),
	nextjs: () => import('@/public/icons/nextjs.png'),
	git: () => import('@/public/icons/git.png'),
	webpack: () => import('@/public/icons/webpack.png'),
	vitejs: () => import('@/public/icons/vitejs.png'),
	reactquery: () => import('@/public/icons/reactquery.png'),
	nodejs: () => import('@/public/icons/nodejs.png'),
	gulp: () => import('@/public/icons/gulp.png'),
	gitlab: () => import('@/public/icons/gitlab.png'),
	github: () => import('@/public/icons/github.png'),
	wordpress: () => import('@/public/icons/wordpress.png'),
	sass: () => import('@/public/icons/sass.png'),
	eslint: () => import('@/public/icons/eslint.png'),
	prettier: () => import('@/public/icons/prettier.png'),
	antd: () => import('@/public/icons/antd.png'),
	markdown: () => import('@/public/icons/markdown.png'),
	zod: () => import('@/public/icons/zod.png'),
}

